content = (
    "<?php\n"
    "\n"
    "namespace App\\Controllers;\n"
    "\n"
    "use App\\Services\\ImportService;\n"
    "use CodeIgniter\\HTTP\\ResponseInterface;\n"
    "\n"
    "class Import extends BaseController\n"
    "{\n"
    "    // ── Página principal ──────────────────────────────────────\n"
    "\n"
    "    /**\n"
    "     * GET /import\n"
    "     * Muestra el formulario de importación y el historial de los últimos 20 jobs.\n"
    "     */\n"
    "    public function index(): string\n"
    "    {\n"
    "        $db   = \\Config\\Database::connect();\n"
    "        $jobs = $db->table('import_jobs')\n"
    "            ->orderBy('created_at', 'DESC')\n"
    "            ->limit(20)\n"
    "            ->get()\n"
    "            ->getResultArray();\n"
    "\n"
    "        return view('import/index', [\n"
    "            'title'     => 'Importador — Compatibilidades',\n"
    "            'pageTitle' => 'Importador Excel',\n"
    "            'jobs'      => $jobs,\n"
    "        ]);\n"
    "    }\n"
    "\n"
    "    // ── Subir y procesar ──────────────────────────────────────\n"
    "\n"
    "    /**\n"
    "     * POST /import/upload\n"
    "     * Recibe el archivo subido, delega en ImportService::run() y redirige con flashdata.\n"
    "     */\n"
    "    public function upload()\n"
    "    {\n"
    "        $file = $this->request->getFile('archivo');\n"
    "\n"
    "        if (!$file || !$file->isValid() || $file->hasMoved()) {\n"
    "            session()->setFlashdata('error', 'No se recibió ningún archivo válido.');\n"
    "            return redirect()->to(site_url('/import'));\n"
    "        }\n"
    "\n"
    "        $tmpPath = WRITEPATH . 'uploads/tmp_' . $file->getRandomName();\n"
    "        $file->move(WRITEPATH . 'uploads/', basename($tmpPath));\n"
    "\n"
    "        $nativeFile = [\n"
    "            'name'     => $file->getClientName(),\n"
    "            'tmp_name' => WRITEPATH . 'uploads/' . basename($tmpPath),\n"
    "            'error'    => UPLOAD_ERR_OK,\n"
    "            'size'     => $file->getSize(),\n"
    "        ];\n"
    "\n"
    "        $service = new ImportService();\n"
    "        $result  = $service->run($nativeFile);\n"
    "\n"
    "        if (file_exists($nativeFile['tmp_name'])) {\n"
    "            @unlink($nativeFile['tmp_name']);\n"
    "        }\n"
    "\n"
    "        if ($result['ok']) {\n"
    "            session()->setFlashdata('success', \"Importación completada. Job #{$result['job_id']}.\");\n"
    "        } else {\n"
    "            session()->setFlashdata('error', $result['error']);\n"
    "        }\n"
    "\n"
    "        return redirect()->to(site_url('/import'));\n"
    "    }\n"
    "\n"
    "    // ── Detalle de un job (HTMX partial) ─────────────────────\n"
    "\n"
    "    /**\n"
    "     * GET /import/job/{id}\n"
    "     *\n"
    "     * @param int $id ID del import_job\n"
    "     */\n"
    "    public function jobDetail(int $id): ResponseInterface\n"
    "    {\n"
    "        $db  = \\Config\\Database::connect();\n"
    "        $job = $db->table('import_jobs')->where('id', $id)->get()->getRowArray();\n"
    "\n"
    "        if (!$job) {\n"
    "            return $this->response->setStatusCode(404)->setBody('<p class=\"text-danger\">Job no encontrado.</p>');\n"
    "        }\n"
    "\n"
    "        $items = $db->table('import_items')\n"
    "            ->where('import_job_id', $id)\n"
    "            ->orderBy('fila_numero', 'ASC')\n"
    "            ->get()\n"
    "            ->getResultArray();\n"
    "\n"
    "        return $this->response->setBody(\n"
    "            view('import/_job_detail', ['job' => $job, 'items' => $items])\n"
    "        );\n"
    "    }\n"
    "\n"
    "    // ── Pendientes de enriquecimiento ─────────────────────────\n"
    "\n"
    "    /**\n"
    "     * GET /import/pendientes\n"
    "     * Endpoint HTMX: devuelve tabla de productos que no pudieron enriquecerse.\n"
    "     */\n"
    "    public function pendientes(): ResponseInterface\n"
    "    {\n"
    "        $db = \\Config\\Database::connect();\n"
    "\n"
    "        $rows = $db->table('productos p')\n"
    "            ->select('p.id, p.nombre, p.clave_proveedor, p.enrich_estado, pr.nombre AS proveedor')\n"
    "            ->join('proveedores pr', 'pr.id = p.proveedor_id', 'left')\n"
    "            ->whereIn('p.enrich_estado', ['sin_tipo', 'sin_moto', 'sin_ambos'])\n"
    "            ->orWhere('p.enrich_estado IS NULL')\n"
    "            ->orderBy('p.enrich_estado')\n"
    "            ->get()\n"
    "            ->getResultArray();\n"
    "\n"
    "        return $this->response->setBody(\n"
    "            view('import/_pendientes', ['pendientes' => $rows])\n"
    "        );\n"
    "    }\n"
    "\n"
    "    // ── Reintento de enriquecimiento ──────────────────────────\n"
    "\n"
    "    /**\n"
    "     * POST /import/reenrich\n"
    "     * Reintenta el enriquecimiento de todos los productos pendientes.\n"
    "     */\n"
    "    public function reenrich(): ResponseInterface\n"
    "    {\n"
    "        $service = new ImportService();\n"
    "        $result  = $service->reenrichPendientes();\n"
    "\n"
    "        session()->setFlashdata(\n"
    "            'success',\n"
    "            \"Reintento completado: {$result['ok']} enriquecidos, {$result['pendientes']} aún pendientes.\"\n"
    "        );\n"
    "\n"
    "        return $this->response\n"
    "            ->setHeader('HX-Redirect', site_url('/import'))\n"
    "            ->setBody('');\n"
    "    }\n"
    "}\n"
)

with open(
    r"d:\htdocs\sharkmotors\catalogo-compatibilidades\app\Controllers\Import.php",
    "w",
    encoding="utf-8",
    newline="\n",
) as f:
    f.write(content)

print("Import.php escrito correctamente")
